"""Shared constants for ftn-audit."""

from __future__ import annotations


LOGGER_AUDIT = "audit"
LOGGER_AUDIT_M2M = "audit.m2m"
LOGGER_AUDIT_OTLP = "audit.otlp"

TASK_EMIT_AUDIT_LOG = "ftn_audit.emit_audit_log"
OTEL_LOGGER_NAME = "ftn_audit"

EVENT_CREATION = "creation"
EVENT_UPDATE = "update"
EVENT_DELETION = "deletion"
EVENT_COLLECTION_UPDATE = "collection_update"

M2M_ACTION_PRE_CLEAR = "pre_clear"
M2M_ACTION_POST_ADD = "post_add"
M2M_ACTION_POST_REMOVE = "post_remove"
M2M_ACTION_POST_CLEAR = "post_clear"
M2M_TRACKED_ACTIONS = (
    M2M_ACTION_PRE_CLEAR,
    M2M_ACTION_POST_ADD,
    M2M_ACTION_POST_REMOVE,
    M2M_ACTION_POST_CLEAR,
)

ATTR_EVENT_TYPE = "audit.event_type"
ATTR_MODEL = "audit.model"
ATTR_MODEL_PK = "audit.model_pk"
ATTR_RAW_ROUTE = "audit.raw_route"
ATTR_CHANGESET = "audit.changeset"
ATTR_FIELD_NAME = "audit.field_name"
ATTR_ACTION = "audit.action"
ATTR_PK_SET = "audit.pk_set"

M2M_PK_SET_MAX = 500

SETTING_AUDIT_ENABLED = "AUDIT_ENABLED"
SETTING_AUDIT_DELIVERY_MODE = "AUDIT_DELIVERY_MODE"
SETTING_AUDIT_OTLP_FALLBACK = "AUDIT_OTLP_FALLBACK"
SETTING_AUDIT_STRICT_FORMATTER_VALIDATION = "AUDIT_STRICT_FORMATTER_VALIDATION"
SETTING_AUDIT_AUTO_CONNECT_SIGNALS = "AUDIT_AUTO_CONNECT_SIGNALS"
SETTING_AUDIT_AUTO_DISCOVER_FORMATTERS = "AUDIT_AUTO_DISCOVER_FORMATTERS"
SETTING_AUDIT_CHANGESET_CHECK_RELATIONSHIP = "AUDIT_CHANGESET_CHECK_RELATIONSHIP"

DELIVERY_MODE_CELERY = "celery"
DELIVERY_MODE_SYNC = "sync"
DELIVERY_MODE_NOOP = "noop"

FALLBACK_MODE_STRUCTURED_LOG = "structured_log"
FALLBACK_MODE_DROP = "drop"

DEFAULT_AUDIT_ENABLED = True
DEFAULT_DELIVERY_MODE = DELIVERY_MODE_CELERY
DEFAULT_FALLBACK_MODE = FALLBACK_MODE_STRUCTURED_LOG
DEFAULT_STRICT_FORMATTER_VALIDATION = True
DEFAULT_AUTO_CONNECT_SIGNALS = True
DEFAULT_AUTO_DISCOVER_FORMATTERS = True
DEFAULT_CHANGESET_CHECK_RELATIONSHIP = False

DEFAULT_TASK_MAX_RETRIES = 2
DEFAULT_TASK_RETRY_DELAY_SECONDS = 5

DEFAULT_IGNORED_CHANGE_FIELDS = (
    "created",
    "modified",
    "created_at",
    "updated_at",
    "created_by",
    "updated_by",
)

DISPATCH_UID_PRE_SAVE = "ftn_audit_pre_save"
DISPATCH_UID_POST_SAVE = "ftn_audit_post_save"
DISPATCH_UID_POST_DELETE = "ftn_audit_post_delete"
DISPATCH_UID_M2M_CHANGED = "ftn_audit_m2m_changed"
